// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reciclajejuego.AppMVC.Models;

#nullable disable

namespace Reciclajejuego.AppMVC.Migrations
{
    [DbContext(typeof(ReciclajeJuegoContext))]
    partial class ReciclajeJuegoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.Ajuste", b =>
                {
                    b.Property<int>("AjustesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ajustesID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AjustesId"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioID");

                    b.Property<int>("VolumenEfectos")
                        .HasColumnType("int")
                        .HasColumnName("volumenEfectos");

                    b.Property<int>("VolumenGeneral")
                        .HasColumnType("int")
                        .HasColumnName("volumenGeneral");

                    b.Property<int>("VolumenMusica")
                        .HasColumnType("int")
                        .HasColumnName("volumenMusica");

                    b.HasKey("AjustesId")
                        .HasName("PK__ajustes__A16CB44DF02AB26F");

                    b.HasIndex(new[] { "UsuarioId" }, "UQ__ajustes__A5B1ABAF6893CD46")
                        .IsUnique();

                    b.ToTable("ajustes", (string)null);
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.Contenedor", b =>
                {
                    b.Property<int>("ContenedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contenedorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContenedorId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("color");

                    b.Property<string>("TipoReciclaje")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipoReciclaje");

                    b.HasKey("ContenedorId")
                        .HasName("PK__contened__2FA199F7FB5D0EFE");

                    b.HasIndex(new[] { "TipoReciclaje" }, "UQ__contened__98E9429C8370BF4B")
                        .IsUnique();

                    b.ToTable("contenedor", (string)null);
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.DetallesModo", b =>
                {
                    b.Property<int>("ModoJuegoId")
                        .HasColumnType("int")
                        .HasColumnName("modoJuegoID");

                    b.Property<int?>("ComboMaximo")
                        .HasColumnType("int")
                        .HasColumnName("comboMaximo");

                    b.Property<int?>("TiempoLimite")
                        .HasColumnType("int")
                        .HasColumnName("tiempoLimite");

                    b.Property<int?>("Vidas")
                        .HasColumnType("int")
                        .HasColumnName("vidas");

                    b.HasKey("ModoJuegoId")
                        .HasName("PK__detalles__751590887E8576D2");

                    b.ToTable("detalles_modo", (string)null);
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.Juego", b =>
                {
                    b.Property<int>("JuegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("juegoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JuegoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaInicio")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ModoJuegoId")
                        .HasColumnType("int")
                        .HasColumnName("modoJuegoID");

                    b.Property<int>("PuntuacionActual")
                        .HasColumnType("int")
                        .HasColumnName("puntuacionActual");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioID");

                    b.HasKey("JuegoId")
                        .HasName("PK__juego__B68069B5CDD02967");

                    b.HasIndex("ModoJuegoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("juego", (string)null);
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.ModoJuego", b =>
                {
                    b.Property<int>("ModoJuegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("modoJuegoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModoJuegoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("ModoJuegoId")
                        .HasName("PK__modo_jue__751590880755731C");

                    b.HasIndex(new[] { "Nombre" }, "UQ__modo_jue__72AFBCC62F4FD23B")
                        .IsUnique();

                    b.ToTable("modo_juego", (string)null);
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.Residuo", b =>
                {
                    b.Property<int>("ResiduoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("residuoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResiduoId"));

                    b.Property<int>("ContenedorId")
                        .HasColumnType("int")
                        .HasColumnName("contenedorID");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Imagen")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Puntos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("puntos");

                    b.HasKey("ResiduoId")
                        .HasName("PK__residuo__B9516E472974259E");

                    b.HasIndex("ContenedorId");

                    b.ToTable("residuo", (string)null);
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<bool>("CuentaGoogle")
                        .HasColumnType("bit")
                        .HasColumnName("cuentaGoogle");

                    b.Property<int>("MejorPuntaje")
                        .HasColumnType("int")
                        .HasColumnName("mejorPuntaje");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("UsuarioId")
                        .HasName("PK__usuario__A5B1ABAEB259978B");

                    b.HasIndex(new[] { "Correo" }, "UQ__usuario__2A586E0BE80BD6F9")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.Ajuste", b =>
                {
                    b.HasOne("Reciclajejuego.AppMVC.Models.Usuario", "Usuario")
                        .WithOne("Ajuste")
                        .HasForeignKey("Reciclajejuego.AppMVC.Models.Ajuste", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ajustes__usuario__534D60F1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.DetallesModo", b =>
                {
                    b.HasOne("Reciclajejuego.AppMVC.Models.ModoJuego", "ModoJuego")
                        .WithOne("DetallesModo")
                        .HasForeignKey("Reciclajejuego.AppMVC.Models.DetallesModo", "ModoJuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__detalles___modoJ__59063A47");

                    b.Navigation("ModoJuego");
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.Juego", b =>
                {
                    b.HasOne("Reciclajejuego.AppMVC.Models.ModoJuego", "ModoJuego")
                        .WithMany("Juegos")
                        .HasForeignKey("ModoJuegoId")
                        .IsRequired()
                        .HasConstraintName("FK__juego__modoJuego__6754599E");

                    b.HasOne("Reciclajejuego.AppMVC.Models.Usuario", "Usuario")
                        .WithMany("Juegos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__juego__usuarioID__66603565");

                    b.Navigation("ModoJuego");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.Residuo", b =>
                {
                    b.HasOne("Reciclajejuego.AppMVC.Models.Contenedor", "Contenedor")
                        .WithMany("Residuos")
                        .HasForeignKey("ContenedorId")
                        .IsRequired()
                        .HasConstraintName("FK__residuo__contene__5FB337D6");

                    b.Navigation("Contenedor");
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.Contenedor", b =>
                {
                    b.Navigation("Residuos");
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.ModoJuego", b =>
                {
                    b.Navigation("DetallesModo");

                    b.Navigation("Juegos");
                });

            modelBuilder.Entity("Reciclajejuego.AppMVC.Models.Usuario", b =>
                {
                    b.Navigation("Ajuste");

                    b.Navigation("Juegos");
                });
#pragma warning restore 612, 618
        }
    }
}
